language: php

sudo: false

php:
  - 7.0
  - 5.6
  - 5.5
  - 5.4
  - hhvm

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm

env:
  global:
  - DB=mysql
  - secure: rHzH5GDl7vGz1jq0Xb4WD2Z0hC94A9kHCxMrkuiZZm/oqn+Abt0mkwwO9K23GXtxEaoCQcgoF4ogs6T7lMZHaINEVfwNHix+TfF7macDWPESdHFdo01haONoPf2ZfqI5zEb28dYvYMvOwVD1r3sbadNvSSNf16lDDUx+aNUwXqw=
  - secure: RceQiWqq7eknG2MPN8IlpdH7nfGaqe7xm17vQndfbXPuED8a87dU4lJHPWCInaqcYte1IDmYsqR59+Ksq8ryC0CbScCf+QKT6kY6FwnzzPCzTU88FrYRXXRbJdfodHb3QTRY747ek4sBdUyaG8Jq28lHH8ZbM6onqrOyylf+pA8=

addons:
  #uncomment the following to trigger webtests
#  sauce_connect: true

services: memcached

git:
  submodules: false

before_install:
  - travis_retry composer self-update -q
  - if [ -n "$GH_TOKEN" ]; then composer config github-oauth.github.com ${GH_TOKEN}; fi;

install:
  - travis_wait composer install --no-interaction

branches:
  except:
  - "/^v15.*$/"

before_script:
  - touch includes/configure.php
  - touch admin/includes/configure.php
  # php
#  - echo 'date.timezone = "Europe/London"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  # mysql
  - mysql --execute="create database IF NOT EXISTS zencart;" --user=travis
  # set up apache server and vhost
#  - bash testFramework/setup/do-apache.sh
  # sauce setup
#  - bash testFramework/setup/do-sauce.sh
  - mkdir -p build/logs

script:
  - php vendor/bin/phpunit -c testFramework/unittests/phpunit.xml
  #uncomment the following to trigger webtests
#  - testFramework/webtests/vendor/bin/phpunit testFramework/webtests/allWebTests.php

after_script:
  #- vendor/bin/phpcs --standard=PSR2 includes/ testFramework/
  #- php vendor/bin/coveralls
  #- vendor/bin/phpmd includes/ text cleancode,codesize,controversial,design,naming,unusedcode

notifications:
  slack:
    secure: srX7adSXCcUZKL26uVDUSwjZmIz9+l93G78RXOFY+nTvh1WMgjyYKdoSWLM9HanCBbMGuQ2xYup/w6Bl7yIwyo6ubgigGG1pIqlfLDaa8BPvV+K6p9XD5tK9izrzHK6T6Z/NHIuC41Tjka4IXT424aIPmsN5SkcfbWHeLuX6WOo=

