name: Zen Cart Unit Tests

on: [push, pull_request]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['8.0', '8.1', '8.2', '8.3']
    continue-on-error: ${{ matrix.php == '8.3' }}
    name: PHP ${{ matrix.php-versions }} Unit Tests
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          tools: composer, phpunit

      - name: Cache composer dependencies
        uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          path: ${{ steps.composer-cache.outputs.dir }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install Composer dependencies
        run: composer install --no-progress --no-interaction --no-suggest --ignore-platform-reqs --prefer-dist --optimize-autoloader --no-ansi --no-scripts

      - name: Prepare the application
        run: |
          touch includes/configure.php

      - name: Run UnitTests suite
        run: php vendor/bin/phpunit --verbose --process-isolation --testsuite=Unit --debug

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: artifacts
          path: not_for_release/testFramework/logs/console
          if-no-files-found: error
          retention-days: 90
